import type {  ProductsType } from "@/types/ProductsType";

export const products:ProductsType[] = [
  {
    id: "prod-1",
    name: "Men Casual Shirt",
    slug: "men-casual-shirt",
    description: "Premium cotton shirt for daily wear.",
    price: 1800,
    discountPrice: 1500,
    category: "men",
    brand: "Zara",
    stock: 25,
    rating: 4.5,
    reviewCount: 12,
    isFeatured: true,
    variants: [
      { color: "Black", size: "S", image : "/image/men-polo-shirtblack.jpg" },
      { color: "Black", size: "M", image : "/image/men-polo-shirtblack.jpg" },
      { color: "Blue", size: "L", image: '/image/portrait-handsome-smiling-hipster-lumbersexual-businessman-model-wearing-casual-jeans-shirt-clothes.jpg' },
      { color: "Red", size: "M", image: "/image/download (1).jpg" },
    ],
  },
  {
    id: "prod-2",
    name: "Women Summer Dress",
    slug: "women-summer-dress",
    description: "Elegant floral summer dress for women.",
    price: 2500,
    discountPrice: 2200,
    category: "women",
    brand: "H&M",
    stock: 15,
    rating: 4.8,
    reviewCount: 20,
    isFeatured: true,
    variants: [
      { color: "Red", size: "S", image: '/image/download (2).jpg' },
      { color: "Red", size: "M", image: '/image/download (3).jpg' },
      { color: "Pink", size: "M", image: '/image/pink.jpg' },
      { color: "Pink", size: "L", image: '/image/pink2.jpg' },
    ],
  },
  {
    id: "prod-3",
    name: "Men Formal Shirt",
    slug: "men-formal-shirt",
    description: "Slim fit formal shirt for office.",
    price: 2200,
    category: "men",
    brand: "Arrow",
    stock: 10,
    rating: 4.3,
    reviewCount: 8,
    isFeatured: false,
    variants: [
      { color: "White", size: "M", image: "/image/formal.jpg" },
      { color: "Blue", size: "L", image: "/image/smiling-man-wearing-sunglasses.jpg" },
    ],
  },
  {
    id: "prod-4",
    name: "Women Evening Gown",
    slug: "women-evening-gown",
    description: "Luxury evening gown for special occasions.",
    price: 4500,
    discountPrice: 4000,
    category: "women",
    brand: "Forever21",
    stock: 7,
    rating: 4.9,
    reviewCount: 15,
    isFeatured: true,
    variants: [
      { color: "Black", size: "S", image: "/image/women-evening-gownbalck.jpg" },
      { color: "Black", size: "M", image: "/image/women-evening-gownblack2.jpg" },
      { color: "Red", size: "M", image: "/image/women-evening-gownred.jpg" },
    ],
  },
  {
    id: "prod-5",
    name: "Kids T-shirt",
    slug: "kids-tshirt",
    description: "Soft cotton t-shirt for kids.",
    price: 900,
    category: "kids",
    brand: "GAP",
    stock: 30,
    rating: 4.6,
    reviewCount: 5,
    isFeatured: false,
    variants: [
      { color: "Blue", size: "S", image: "/image/kids-tshirtblue.jpg" },
      { color: "Yellow", size: "M", image: "/image/kids-tshirtyellow.jpg" },
      { color: "Red", size: "L", image: "/image/kids-tshirtred.jpg" },
    ],
  },
  {
    id: "prod-6",
    name: "Men Polo Shirt",
    slug: "men-polo-shirt",
    description: "Casual Polo shirt for men.",
    price: 2000,
    category: "men",
    brand: "Levis",
    stock: 12,
    rating: 4.2,
    reviewCount: 6,
    isFeatured: true,
    variants: [
      { color: "Green", size: "M", image: "/image/men-polo-shirtgreen.jpg" },
      { color: "White", size: "L", image: "/image/men-polo-shirtwhite.jpg" },
      { color: "Black", size: "XL", image: "/image/men-polo-shirtblack.jpg" },
    ],
  },
  {
    id: "prod-7",
    name: "Men Casual Shirt",
    slug: "men-casual-shirt",
    description: "Premium cotton shirt for daily wear.",
    price: 1800,
    discountPrice: 1500,
    category: "men",
    brand: "Zara",
    stock: 25,
    rating: 4.5,
    reviewCount: 12,
    isFeatured: true,
    variants: [
      { color: "Black", size: "S", image : "/image/men-polo-shirtblack.jpg" },
      { color: "Black", size: "M", image : "/image/men-polo-shirtblack.jpg" },
      { color: "Blue", size: "L", image: '/image/portrait-handsome-smiling-hipster-lumbersexual-businessman-model-wearing-casual-jeans-shirt-clothes.jpg' },
      { color: "Red", size: "M", image: "/image/download (1).jpg" },
    ],
  },
  {
    id: "prod-8",
    name: "Women Summer Dress",
    slug: "women-summer-dress",
    description: "Elegant floral summer dress for women.",
    price: 2500,
    discountPrice: 2200,
    category: "women",
    brand: "H&M",
    stock: 15,
    rating: 4.8,
    reviewCount: 20,
    isFeatured: true,
    variants: [
      { color: "Red", size: "S", image: '/image/download (2).jpg' },
      { color: "Red", size: "M", image: '/image/download (3).jpg' },
      { color: "Pink", size: "M", image: '/image/pink.jpg' },
      { color: "Pink", size: "L", image: '/image/pink2.jpg' },
    ],
  },
  {
    id: "prod-9",
    name: "Men Formal Shirt",
    slug: "men-formal-shirt",
    description: "Slim fit formal shirt for office.",
    price: 2200,
    category: "men",
    brand: "Arrow",
    stock: 10,
    rating: 4.3,
    reviewCount: 8,
    isFeatured: false,
    variants: [
      { color: "White", size: "M", image: "/image/formal.jpg" },
      { color: "Blue", size: "L", image: "/image/smiling-man-wearing-sunglasses.jpg" },
    ],
  },
  {
    id: "prod-10",
    name: "Women Evening Gown",
    slug: "women-evening-gown",
    description: "Luxury evening gown for special occasions.",
    price: 4500,
    discountPrice: 4000,
    category: "women",
    brand: "Forever21",
    stock: 7,
    rating: 4.9,
    reviewCount: 15,
    isFeatured: true,
    variants: [
      { color: "Black", size: "S", image: "/image/women-evening-gownbalck.jpg" },
      { color: "Black", size: "M", image: "/image/women-evening-gownblack2.jpg" },
      { color: "Red", size: "M", image: "/image/women-evening-gownred.jpg" },
    ],
  },
  {
    id: "prod-11",
    name: "Kids T-shirt",
    slug: "kids-tshirt",
    description: "Soft cotton t-shirt for kids.",
    price: 900,
    category: "kids",
    brand: "GAP",
    stock: 30,
    rating: 4.6,
    reviewCount: 5,
    isFeatured: false,
    variants: [
      { color: "Blue", size: "S", image: "/image/kids-tshirtblue.jpg" },
      { color: "Yellow", size: "M", image: "/image/kids-tshirtyellow.jpg" },
      { color: "Red", size: "L", image: "/image/kids-tshirtred.jpg" },
    ],
  },
  {
    id: "prod-12",
    name: "Men Polo Shirt",
    slug: "men-polo-shirt",
    description: "Casual Polo shirt for men.",
    price: 2000,
    category: "men",
    brand: "Levis",
    stock: 12,
    rating: 4.2,
    reviewCount: 6,
    isFeatured: true,
    variants: [
      { color: "Green", size: "M", image: "/image/men-polo-shirtgreen.jpg" },
      { color: "White", size: "L", image: "/image/men-polo-shirtwhite.jpg" },
      { color: "Black", size: "XL", image: "/image/men-polo-shirtblack.jpg" },
    ],
  },
  {
    id: "prod-13",
    name: "Men Casual Shirt",
    slug: "men-casual-shirt",
    description: "Premium cotton shirt for daily wear.",
    price: 1800,
    discountPrice: 1500,
    category: "men",
    brand: "Zara",
    stock: 25,
    rating: 4.5,
    reviewCount: 12,
    isFeatured: true,
    variants: [
      { color: "Black", size: "S", image : "/image/men-polo-shirtblack.jpg" },
      { color: "Black", size: "M", image : "/image/men-polo-shirtblack.jpg" },
      { color: "Blue", size: "L", image: '/image/portrait-handsome-smiling-hipster-lumbersexual-businessman-model-wearing-casual-jeans-shirt-clothes.jpg' },
      { color: "Red", size: "M", image: "/image/download (1).jpg" },
    ],
  },
  {
    id: "prod-14",
    name: "Women Summer Dress",
    slug: "women-summer-dress",
    description: "Elegant floral summer dress for women.",
    price: 2500,
    discountPrice: 2200,
    category: "women",
    brand: "H&M",
    stock: 15,
    rating: 4.8,
    reviewCount: 20,
    isFeatured: true,
    variants: [
      { color: "Red", size: "S", image: '/image/download (2).jpg' },
      { color: "Red", size: "M", image: '/image/download (3).jpg' },
      { color: "Pink", size: "M", image: '/image/pink.jpg' },
      { color: "Pink", size: "L", image: '/image/pink2.jpg' },
    ],
  },
  {
    id: "prod-15",
    name: "Men Formal Shirt",
    slug: "men-formal-shirt",
    description: "Slim fit formal shirt for office.",
    price: 2200,
    category: "men",
    brand: "Arrow",
    stock: 10,
    rating: 4.3,
    reviewCount: 8,
    isFeatured: false,
    variants: [
      { color: "White", size: "M", image: "/image/formal.jpg" },
      { color: "Blue", size: "L", image: "/image/smiling-man-wearing-sunglasses.jpg" },
    ],
  },
  {
    id: "prod-16",
    name: "Women Evening Gown",
    slug: "women-evening-gown",
    description: "Luxury evening gown for special occasions.",
    price: 4500,
    discountPrice: 4000,
    category: "women",
    brand: "Forever21",
    stock: 7,
    rating: 4.9,
    reviewCount: 15,
    isFeatured: true,
    variants: [
      { color: "Black", size: "S", image: "/image/women-evening-gownbalck.jpg" },
      { color: "Black", size: "M", image: "/image/women-evening-gownblack2.jpg" },
      { color: "Red", size: "M", image: "/image/women-evening-gownred.jpg" },
    ],
  },
  {
    id: "prod-17",
    name: "Kids T-shirt",
    slug: "kids-tshirt",
    description: "Soft cotton t-shirt for kids.",
    price: 900,
    category: "kids",
    brand: "GAP",
    stock: 30,
    rating: 4.6,
    reviewCount: 5,
    isFeatured: false,
    variants: [
      { color: "Blue", size: "S", image: "/image/kids-tshirtblue.jpg" },
      { color: "Yellow", size: "M", image: "/image/kids-tshirtyellow.jpg" },
      { color: "Red", size: "L", image: "/image/kids-tshirtred.jpg" },
    ],
  },
  {
    id: "prod-18",
    name: "Men Polo Shirt",
    slug: "men-polo-shirt",
    description: "Casual Polo shirt for men.",
    price: 2000,
    category: "men",
    brand: "Levis",
    stock: 12,
    rating: 4.2,
    reviewCount: 6,
    isFeatured: true,
    variants: [
      { color: "Green", size: "M", image: "/image/men-polo-shirtgreen.jpg" },
      { color: "White", size: "L", image: "/image/men-polo-shirtwhite.jpg" },
      { color: "Black", size: "XL", image: "/image/men-polo-shirtblack.jpg" },
    ],
  },
  {
    id: "prod-20",
    name: "Men Casual Shirt",
    slug: "men-casual-shirt",
    description: "Premium cotton shirt for daily wear.",
    price: 1800,
    discountPrice: 1500,
    category: "men",
    brand: "Zara",
    stock: 25,
    rating: 4.5,
    reviewCount: 12,
    isFeatured: true,
    variants: [
      { color: "Black", size: "S", image : "/image/men-polo-shirtblack.jpg" },
      { color: "Black", size: "M", image : "/image/men-polo-shirtblack.jpg" },
      { color: "Blue", size: "L", image: '/image/portrait-handsome-smiling-hipster-lumbersexual-businessman-model-wearing-casual-jeans-shirt-clothes.jpg' },
      { color: "Red", size: "M", image: "/image/download (1).jpg" },
    ],
  },
  {
    id: "prod-21",
    name: "Women Summer Dress",
    slug: "women-summer-dress",
    description: "Elegant floral summer dress for women.",
    price: 2500,
    discountPrice: 2200,
    category: "women",
    brand: "H&M",
    stock: 15,
    rating: 4.8,
    reviewCount: 20,
    isFeatured: true,
    variants: [
      { color: "Red", size: "S", image: '/image/download (2).jpg' },
      { color: "Red", size: "M", image: '/image/download (3).jpg' },
      { color: "Pink", size: "M", image: '/image/pink.jpg' },
      { color: "Pink", size: "L", image: '/image/pink2.jpg' },
    ],
  },
  {
    id: "prod-22",
    name: "Men Formal Shirt",
    slug: "men-formal-shirt",
    description: "Slim fit formal shirt for office.",
    price: 2200,
    category: "men",
    brand: "Arrow",
    stock: 10,
    rating: 4.3,
    reviewCount: 8,
    isFeatured: false,
    variants: [
      { color: "White", size: "M", image: "/image/formal.jpg" },
      { color: "Blue", size: "L", image: "/image/smiling-man-wearing-sunglasses.jpg" },
    ],
  },
  {
    id: "prod-23",
    name: "Women Evening Gown",
    slug: "women-evening-gown",
    description: "Luxury evening gown for special occasions.",
    price: 4500,
    discountPrice: 4000,
    category: "women",
    brand: "Forever21",
    stock: 7,
    rating: 4.9,
    reviewCount: 15,
    isFeatured: true,
    variants: [
      { color: "Black", size: "S", image: "/image/women-evening-gownbalck.jpg" },
      { color: "Black", size: "M", image: "/image/women-evening-gownblack2.jpg" },
      { color: "Red", size: "M", image: "/image/women-evening-gownred.jpg" },
    ],
  },
  {
    id: "prod-24",
    name: "Kids T-shirt",
    slug: "kids-tshirt",
    description: "Soft cotton t-shirt for kids.",
    price: 900,
    category: "kids",
    brand: "GAP",
    stock: 30,
    rating: 4.6,
    reviewCount: 5,
    isFeatured: false,
    variants: [
      { color: "Blue", size: "S", image: "/image/kids-tshirtblue.jpg" },
      { color: "Yellow", size: "M", image: "/image/kids-tshirtyellow.jpg" },
      { color: "Red", size: "L", image: "/image/kids-tshirtred.jpg" },
    ],
  },
  {
    id: "prod-25",
    name: "Men Polo Shirt",
    slug: "men-polo-shirt",
    description: "Casual Polo shirt for men.",
    price: 2000,
    category: "men",
    brand: "Levis",
    stock: 12,
    rating: 4.2,
    reviewCount: 6,
    isFeatured: true,
    variants: [
      { color: "Green", size: "M", image: "/image/men-polo-shirtgreen.jpg" },
      { color: "White", size: "L", image: "/image/men-polo-shirtwhite.jpg" },
      { color: "Black", size: "XL", image: "/image/men-polo-shirtblack.jpg" },
    ],
  },
];