export const products = [
  {
    id: "prod-1",
    name: "Men Casual Shirt",
    slug: "men-casual-shirt",
    description: "Premium cotton shirt for daily wear.",
    price: 1800,
    discountPrice: 1500,
    category: "men",
    brand: "Zara",
    stock: 25,
    rating: 4.5,
    reviewCount: 12,
    isFeatured: true,
    variants: [
      { color: "Black", size: "S", images: ["/images/products/shirt1-black-s.jpg"] },
      { color: "Black", size: "M", images: ["/images/products/shirt1-black-m.jpg"] },
      { color: "Blue", size: "L", images: ["/images/products/shirt1-blue-l.jpg"] },
      { color: "Red", size: "M", images: ["/images/products/shirt1-red-m.jpg"] },
    ],
  },
  {
    id: "prod-2",
    name: "Women Summer Dress",
    slug: "women-summer-dress",
    description: "Elegant floral summer dress for women.",
    price: 2500,
    discountPrice: 2200,
    category: "women",
    brand: "H&M",
    stock: 15,
    rating: 4.8,
    reviewCount: 20,
    isFeatured: true,
    variants: [
      { color: "Red", size: "S", images: ["/images/products/dress1-red-s.jpg"] },
      { color: "Red", size: "M", images: ["/images/products/dress1-red-m.jpg"] },
      { color: "Pink", size: "M", images: ["/images/products/dress1-pink-m.jpg"] },
      { color: "Pink", size: "L", images: ["/images/products/dress1-pink-l.jpg"] },
    ],
  },
  {
    id: "prod-3",
    name: "Men Formal Shirt",
    slug: "men-formal-shirt",
    description: "Slim fit formal shirt for office.",
    price: 2200,
    category: "men",
    brand: "Arrow",
    stock: 10,
    rating: 4.3,
    reviewCount: 8,
    isFeatured: false,
    variants: [
      { color: "White", size: "M", images: ["/images/products/shirt2-white-m.jpg"] },
      { color: "Blue", size: "L", images: ["/images/products/shirt2-blue-l.jpg"] },
    ],
  },
  {
    id: "prod-4",
    name: "Women Evening Gown",
    slug: "women-evening-gown",
    description: "Luxury evening gown for special occasions.",
    price: 4500,
    discountPrice: 4000,
    category: "women",
    brand: "Forever21",
    stock: 7,
    rating: 4.9,
    reviewCount: 15,
    isFeatured: true,
    variants: [
      { color: "Black", size: "S", images: ["/images/products/gown-black-s.jpg"] },
      { color: "Black", size: "M", images: ["/images/products/gown-black-m.jpg"] },
      { color: "Red", size: "M", images: ["/images/products/gown-red-m.jpg"] },
    ],
  },
  {
    id: "prod-5",
    name: "Kids T-shirt",
    slug: "kids-tshirt",
    description: "Soft cotton t-shirt for kids.",
    price: 900,
    category: "kids",
    brand: "GAP",
    stock: 30,
    rating: 4.6,
    reviewCount: 5,
    isFeatured: false,
    variants: [
      { color: "Blue", size: "S", images: ["/images/products/kid-shirt-blue-s.jpg"] },
      { color: "Yellow", size: "M", images: ["/images/products/kid-shirt-yellow-m.jpg"] },
      { color: "Red", size: "L", images: ["/images/products/kid-shirt-red-l.jpg"] },
    ],
  },
  {
    id: "prod-6",
    name: "Men Polo Shirt",
    slug: "men-polo-shirt",
    description: "Casual Polo shirt for men.",
    price: 2000,
    category: "men",
    brand: "Levis",
    stock: 12,
    rating: 4.2,
    reviewCount: 6,
    isFeatured: true,
    variants: [
      { color: "Green", size: "M", images: ["/images/products/polo-green-m.jpg"] },
      { color: "White", size: "L", images: ["/images/products/polo-white-l.jpg"] },
      { color: "Black", size: "XL", images: ["/images/products/polo-black-xl.jpg"] },
    ],
  },
  {
    id: "prod-7",
    name: "Women Casual Top",
    slug: "women-casual-top",
    description: "Trendy casual top for women.",
    price: 1500,
    discountPrice: 1300,
    category: "women",
    brand: "Forever21",
    stock: 18,
    rating: 4.4,
    reviewCount: 10,
    isFeatured: false,
    variants: [
      { color: "Pink", size: "S", images: ["/images/products/top-pink-s.jpg"] },
      { color: "Blue", size: "M", images: ["/images/products/top-blue-m.jpg"] },
      { color: "White", size: "L", images: ["/images/products/top-white-l.jpg"] },
    ],
  },
  {
    id: "prod-8",
    name: "Men Jacket",
    slug: "men-jacket",
    description: "Stylish winter jacket for men.",
    price: 3500,
    category: "men",
    brand: "Levis",
    stock: 8,
    rating: 4.7,
    reviewCount: 14,
    isFeatured: true,
    variants: [
      { color: "Black", size: "M", images: ["/images/products/jacket-black-m.jpg"] },
      { color: "Grey", size: "L", images: ["/images/products/jacket-grey-l.jpg"] },
    ],
  },
  {
    id: "prod-9",
    name: "Women Summer Skirt",
    slug: "women-summer-skirt",
    description: "Light and comfortable summer skirt.",
    price: 1800,
    category: "women",
    brand: "H&M",
    stock: 20,
    rating: 4.5,
    reviewCount: 9,
    isFeatured: true,
    variants: [
      { color: "Yellow", size: "S", images: ["/images/products/skirt-yellow-s.jpg"] },
      { color: "Red", size: "M", images: ["/images/products/skirt-red-m.jpg"] },
      { color: "Pink", size: "L", images: ["/images/products/skirt-pink-l.jpg"] },
    ],
  },
  {
    id: "prod-10",
    name: "Kids Dress",
    slug: "kids-dress",
    description: "Cute cotton dress for kids.",
    price: 1200,
    category: "kids",
    brand: "GAP",
    stock: 15,
    rating: 4.8,
    reviewCount: 11,
    isFeatured: true,
    variants: [
      { color: "Pink", size: "S", images: ["/images/products/kid-dress-pink-s.jpg"] },
      { color: "Blue", size: "M", images: ["/images/products/kid-dress-blue-m.jpg"] },
      { color: "Yellow", size: "L", images: ["/images/products/kid-dress-yellow-l.jpg"] },
    ],
  },
];